services:
  - type: web
    name: auction-tracker
    env: python
    plan: free
    autoDeploy: true
    rootDir: auction_tracker
    buildCommand: "pip install --upgrade && pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: TSM_API_KEY
        sync: false

cronJobs:
  - name: refresh-auction-tracker
    schedule: "@every 6h"
    path: "/refresh"
    serviceName: auction-tracker
