services:
  - type: web
    name: core
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py migrate"
    startCommand: "gunicorn core.wsgi:application"
    plan: free
    autoDeploy: true
