services:
  - type: web
    name: core
    env: python
    plan: free
    autoDeploy: true
    rootDir: core
    buildCommand: "pip install --upgrade pip && pip install -r ../requirements.txt"
    startCommand: "python manage.py makemigrations core && python manage.py migrate && python manage.py collectstatic --noinput && python manage.py shell -c \"from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.filter(username='admin').exists() or User.objects.create_superuser('admin', 'admin@example.com', 'your_secure_password')\" && gunicorn core.wsgi:application"

  - type: web
    name: rssfeed
    env: docker
    plan: free
    autoDeploy: true
    rootDir: rssfeed
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: LOGIN_USERNAME
        sync: false
      - key: LOGIN_PASSWORD
        sync: false
      - key: DATABASE_URL
        sync: false

cronJobs:
  - name: refresh-rssfeed
    schedule: "@every 6h"
    path: "/refresh"
    serviceName: rssfeed
