services:
  - type: web
    name: django-render-demo
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py migrate"
    startCommand: "gunicorn pythonbasics.wsgi:application"
    plan: free
    autoDeploy: true
