services:
  - type: web
    name: core
    env: python
    plan: free
    autoDeploy: true
    rootDir: core
    buildCommand: "pip install -r ../requirements.txt && python ../manage.py migrate"
    startCommand: "gunicorn core.wsgi:application"

  - type: web
    name: rssfeed
    env: docker
    plan: free
    autoDeploy: true
    rootDir: rssfeed
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: LOGIN_USERNAME
        sync: false
      - key: LOGIN_PASSWORD
        sync: false

cronJobs:
  - name: refresh-rssfeed
    schedule: "@every 6h"
    path: "/refresh"
    serviceName: rssfeed
